name: Multi-Platform Test

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
      - name: analyze
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install gitlab.com/NebulousLabs/analyze@latest
          make analyze
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ arm64, amd64 ]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^v1.16
      - name: build ${{ matrix.os }}/${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make static
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    needs: [ lint, build ]
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: n8maninger/action-golang-test@503bdd1b410aa26740cad03f1214abc8beef5496
        with:
          args: "-race;-failfast;-tags=testing debug netgo"